# Generated by Django 5.0.2 on 2024-04-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitsupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='fits/')),
            ],
        ),
    ]
